@echo off
rem ==========================================================================
rem uniwill-ec-charge-limit - install_startup.bat
rem
rem Creates a launcher in the CURRENT USER's Startup folder that runs
rem   pythonw.exe <repo>\tools\pin_limit.py --watch 10
rem at every logon. No admin rights required.
rem To uninstall: simply delete the generated file shown below.
rem ==========================================================================
setlocal
set "HERE=%~dp0"
set "STARTUP=%APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup"
set "OUT=%STARTUP%\uniwill-charge-limit-pin.bat"

where pythonw >nul 2>nul
if errorlevel 1 (
    echo [ERROR] pythonw.exe not found on PATH. Install Python 3 ^(python.org^) first.
    pause
    exit /b 1
)

> "%OUT%" echo @echo off
>>"%OUT%" echo rem Auto-generated by uniwill-ec-charge-limit install_startup.bat.
>>"%OUT%" echo rem Re-asserts EC charge-limit pin at logon. Delete this file to disable.
>>"%OUT%" echo start "" /min pythonw.exe "%HERE%pin_limit.py" --watch 10

echo Installed launcher:
echo   %OUT%
echo.
echo Applying one-shot pin now...
python "%HERE%pin_limit.py"
echo.
echo Done. Delete "%OUT%" to remove autostart.
pause
